### ISSUE TITLE
Previous release tags removed

### ISSUE THREAD

**Issue by ivensdenner** [ML-Works/KVO-MVVM#1]
Hello!

Were the tags of the previous releases removed from the repo? I have a project that points to version 0.4.24, and now it can't find it anymore. :(

**Comment by podkovyrin** [comment]
@ivensdenner Sorry about that, we experienced migration.  I've just restored all the tags. Please check it again.

Consider updating to the latest version since there were some bugs in versions prior to 0.5.* that might cause crashes.

**Comment by ivensdenner** [comment]
Thank you @podkovyrin!! 😃

Unfortunately I didn't have time to update to 0.5.* yet, but will do it ASAP.

Thanks!
